# Generated by Django 6.0 on 2026-02-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VegetableCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=2.5, max_digits=10)),
                ('image_url', models.URLField(blank=True)),
                ('rarity', models.CharField(choices=[('common', '🥔 Обычный'), ('uncommon', '🥕 Необычный'), ('rare', '🍅 Редкий'), ('epic', '🍆 Эпический'), ('legendary', '🎃 Легендарный')], default='common', max_length=20)),
                ('drop_chance', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
