# Generated by Django 6.0 on 2026-02-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название кейса')),
                ('description', models.TextField(blank=True, verbose_name='Описание кейса')),
                ('price', models.IntegerField(default=100, verbose_name='Цена открытия')),
                ('image_url', models.URLField(blank=True, verbose_name='Картинка кейса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('emoji', models.CharField(default='🥦', max_length=10, verbose_name='Эмодзи')),
                ('rarity', models.CharField(choices=[('common', '🥔 Обычный'), ('uncommon', '🥕 Необычный'), ('rare', '🍅 Редкий'), ('epic', '🍆 Эпический'), ('legendary', '🎃 Легендарный')], default='common', max_length=20, verbose_name='Редкость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.IntegerField(default=10, verbose_name='Цена в монетах')),
            ],
        ),
        migrations.DeleteModel(
            name='VegetableCase',
        ),
        migrations.AddField(
            model_name='case',
            name='vegetables',
            field=models.ManyToManyField(to='cases.vegetable', verbose_name='Овощи в кейсе'),
        ),
    ]
